# -*- coding: utf-8 -*-
"""Proyecto - Big Mac 12/05/2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zjd9Ua6E48vFH5-p_hgmECEo0ObhcABn

## Inicio: Cargamos la base de datos con Pandas
"""

## Libreria
import pandas as pd

#Variable con ubicacion y nombre del dataset
ubiacion = "/content/drive/MyDrive/Proyecto #3/"
dataset = "dataset_final"

#Incio del dataframe
df = pd.read_csv(ubiacion + dataset)

#Vista del dataframe
df

"""## Informe: Salarios, precios y poder adquisitivo"""

## Salario Mínimo
df.sort_values(by="Salario minimo (USD)", ascending=False, inplace=True)
salario_minimo_mas_alto = df.head(1)
salario_minimo_mas_bajo = df.tail(2)
print("Salario minimo mas alto es entre los paises analizado es de", salario_minimo_mas_alto["Pais"].iloc[0], "con el monto de",salario_minimo_mas_alto["Salario minimo (USD)"].iloc[0], "USD,")
print("el mas bajo (sin tener encuenta a", salario_minimo_mas_bajo["Pais"].iloc[1]+")", "es de", salario_minimo_mas_bajo["Pais"].iloc[0], "con el monto de",salario_minimo_mas_bajo["Salario minimo (USD)"].iloc[0], "USD y")
print("el promedio general es de", df["Salario minimo (USD)"].mean().round(2), "USD.")

## Precio Big Mac
df.sort_values(by="Precio bigmac (USD)", ascending=False, inplace=True)
precio_bigmac_mas_alto = df.head(1)
precio_bigmac_mas_bajo = df.tail(1)
print("El precio más alto de la Big Mac le pertenece a", precio_bigmac_mas_alto["Pais"].iloc[0], "con el monto de",precio_bigmac_mas_alto["Precio bigmac (USD)"].iloc[0], "USD,")
print("el mas barato es de", precio_bigmac_mas_bajo["Pais"].iloc[0], "con el monto de",precio_bigmac_mas_bajo["Precio bigmac (USD)"].iloc[0], "USD y")
print("el promedio general es de", df["Precio bigmac (USD)"].mean().round(2), "USD.")

## Poder Adquisitivo: Big Mac por salario
df.sort_values(by="Cantidad_bigmac_con_salario", ascending=False, inplace=True)
cantidad_bigmac_mayor_x_salario = df.head(1)
cantidad_bigmac_menor_x_salario = df.tail(2)
print("El país con el mayor poder adquisitivo es de", cantidad_bigmac_mayor_x_salario["Pais"].iloc[0]+",", "con el salario minimo permite adquirir", cantidad_bigmac_mayor_x_salario["Cantidad_bigmac_con_salario"].iloc[0], "Big mac,")
print("el mas bajo (sin tener encuenta a", cantidad_bigmac_menor_x_salario["Pais"].iloc[1]+")", "es de", cantidad_bigmac_menor_x_salario["Pais"].iloc[0]+",", "que permite adquirir"\
, cantidad_bigmac_menor_x_salario["Cantidad_bigmac_con_salario"].iloc[0], "Big Mac y")
print("el promedio general es de", df["Cantidad_bigmac_con_salario"].mean().round(2), "Big Mac.")

## Tabla: Países por encima y debajo del promedio de poder adquisitivo
df["Arriba_del_promedio"] = df["Cantidad_bigmac_con_salario"] > df["Cantidad_bigmac_con_salario"].mean().round(2)
arriba_del_promedio = df[df['Arriba_del_promedio']==True].set_index("Pais")
abajo_del_promedio = df[df['Arriba_del_promedio']==False].set_index("Pais")
print("Paises que se encuentra arriba del promedio:")
print("")
print(arriba_del_promedio[["Cantidad_bigmac_con_salario", "Fecha"]])
print("")
print("Paises que se encuentra abajo del promedio:")
print("")
print(abajo_del_promedio[["Cantidad_bigmac_con_salario", "Fecha"]])

"""## Conclusión

Este analisis revela las diferencias de poder adquisitivo entre los países de Sudamérica, basándose en la cantidad de Big Mac que se puede adquirir con el salario mínimo expresado en dólares.
Además, permite observar el costo de vida en el ámbito gastronómico a través del precio de la Big Mac, así como el nivel de salario de cada país en moneda fuerte (USD).
Se observa que, aunque un país tenga un salario mínimo alto, si el costo de vida también es elevado, el poder adquisitivo puede ser considerablemente menor. Un ejemplo de esto es Uruguay.
También se puede dar el caso contrario, como en Brasil: tiene el salario más bajo de la comparación, pero también presenta el costo de vida más bajo, lo que da como resultado un poder adquisitivo por encima del promedio.
El peor escenario se da cuando el salario mínimo es bajo y el costo de vida alto, lo que genera una fuerte pérdida del poder adquisitivo. Un claro ejemplo de esto es Argentina (sin tener encuenta a Venezuela), que se posiciona como uno de los países más caros de la región.
Aclaración: Aunque Venezuela figura en los datos, no se la tiene en cuenta en los análisis debido a su inestabilidad económica y distorsiones en el valor de su moneda.
"""